services:
  app:
    image: ghcr.io/earyanto30/e-spd-kab-banggai-laut:latest
    container_name: espd-kab-banggai-laut
    restart: always
    ports:
      - "80:80"
    volumes:
      # 1. Folder Unggahan Berkas (PDF Kop Surat, Lampiran & Dokumen)
      - /var/compose/espd-kab-banggai-laut/uploads:/app/uploads
      # 2. Folder Database & Data Sistem (SQLite Database dev.db)
      - /var/compose/espd-kab-banggai-laut/data:/app/data
      # 3. Log Nginx (Opsional untuk pemantauan akses & error)
      - /var/compose/espd-kab-banggai-laut/logs:/var/log/nginx
      # 4. File Konfigurasi Environment (.env)
      - /var/compose/espd-kab-banggai-laut/.env:/app/.env

